name = "temp-email"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 生产环境变量（顶层配置）
[vars]
ENVIRONMENT = "production"
BASE_DOMAIN = "api.oooo.icu"
FRONTEND_DOMAIN = "oooo.icu"
JWT_SECRET = "peanut_0806_temp_mail_1Bl8GHds"
TURNSTILE_SECRET_KEY = "0x4AAAAAABo_hIH2pHWgYDUxrP4x6uCZ9EY"
TURNSTILE_SITE_KEY = "0x4AAAAAABo_hK-8xkK5jEPM"
SENDER_DOMAIN = "oooo.icu"
GITHUB_CLIENT_ID = "Ov23liMbRVOzZ5igeF1M"
GITHUB_CLIENT_SECRET = "2fffc1c362e84ad5e5b8f7ad6801d9b7b8b52268"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "oooo-mail"
database_id = "d1144511-217a-4db6-ab72-35f05dff553e"

# 邮件发送配置
[[send_email]]
name = "EMAIL_SENDER"



# 开发环境配置
[env.development]
name = "temp-email-dev"  # 自定义开发环境名称

[env.development.vars]
ENVIRONMENT = "development"
BASE_DOMAIN = "localhost:8787"
FRONTEND_DOMAIN = "localhost:5173"
JWT_SECRET = "peanut_0806_temp_mail_1Bl8GHds"
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"
TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
SENDER_DOMAIN = "oooo.icu"
# GitHub OAuth 配置
GITHUB_CLIENT_ID = "Ov23liMbRVOzZ5igeF1M"
GITHUB_CLIENT_SECRET = "2fffc1c362e84ad5e5b8f7ad6801d9b7b8b52268"

# 开发环境数据库配置
[[env.development.d1_databases]]
binding = "DB"
database_name = "oooo-mail"
database_id = "d1144511-217a-4db6-ab72-35f05dff553e"

# 开发环境邮件发送配置
[[env.development.send_email]]
name = "EMAIL_SENDER"




# 日志分析配置
[observability]
enabled = true
head_sampling_rate = 1

# 构建配置
[build]
command = "npm run build"
