name = "temp-email"
main = "src/index.ts"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "oooo-mail"
database_id = "d1144511-217a-4db6-ab72-35f05dff553e"

# 环境变量
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "dev-jwt-secret-key-for-local-development-only"
BASE_DOMAIN = "localhost"
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"
TURNSTILE_SITE_KEY = "1x00000000000000000000AA"

# 生产环境配置
[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "peanut_0806_temp_mail_1Bl8GHds"
TURNSTILE_SECRET_KEY = "0x4AAAAAABnwzIt8NcyNxRXOCs6EH7npA_Y"
TURNSTILE_SITE_KEY = "0x4AAAAAABnwzPzpwOU-tYrL"

# 开发环境配置
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "dev-jwt-secret-key"
BASE_DOMAIN = "localhost"
TURNSTILE_SECRET_KEY = "dev-turnstile-secret"
TURNSTILE_SITE_KEY = "dev-turnstile-site"


# 构建配置
[build]
command = "npm run build"
