name = "temp-email"
main = "src/index.ts"
compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "oooo-mail"
database_id = "d1144511-217a-4db6-ab72-35f05dff553e"

# 生产环境变量
[env.production.vars]
ENVIRONMENT = "production"
JWT_SECRET = "peanut_0806_temp_mail_1Bl8GHds"
TURNSTILE_SECRET_KEY = "0x4AAAAAABo_hIH2pHWgYDUxrP4x6uCZ9EY"
TURNSTILE_SITE_KEY = "0x4AAAAAABo_hK-8xkK5jEPM"

# 生产环境数据库配置
[[env.production.d1_databases]]
binding = "DB"
database_name = "oooo-mail"
database_id = "d1144511-217a-4db6-ab72-35f05dff553e"

# 生产环境邮件发送配置
[[env.production.send_email]]
name = "SEND_EMAIL"

# 开发环境变量
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "peanut_0806_temp_mail_1Bl8GHds"
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"
TURNSTILE_SITE_KEY = "1x00000000000000000000AA"

# 开发环境数据库配置
[[env.development.d1_databases]]
binding = "DB"
database_name = "oooo-mail"
database_id = "d1144511-217a-4db6-ab72-35f05dff553e"

# 开发环境邮件发送配置
[[env.development.send_email]]
name = "SEND_EMAIL"

# 默认环境变量（开发环境）
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "peanut_0806_temp_mail_1Bl8GHds"
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"
TURNSTILE_SITE_KEY = "1x00000000000000000000AA"

# Cloudflare Send Email API 配置
[[send_email]]
name = "SEND_EMAIL"

# 日志分析配置
[observability]
enabled = true
head_sampling_rate = 1

# 构建配置
[build]
command = "npm run build"
