import { compare, hash } from 'bcryptjs'

const BCRYPT_ROUNDS = 10

export async function hashPassword(password: string): Promise<string> {
  return await hash(password, BCRYPT_ROUNDS)
}

export async function verifyPassword(
  password: string,
  storedHash: string
): Promise<{ valid: boolean; needsRehash: boolean }> {
  if (/^\$2[aby]\$/.test(storedHash)) {
    return { valid: await compare(password, storedHash), needsRehash: false }
  }

  // Compatibility with hashes generated by the old Worker implementation:
  // base64(16-byte salt + 10,001 rounds of SHA-256).
  try {
    const stored = Uint8Array.from(atob(storedHash), character => character.charCodeAt(0))
    if (stored.length === 48) {
      const salt = stored.slice(0, 16)
      const expected = stored.slice(16)
      const passwordBytes = new TextEncoder().encode(password)
      const combined = new Uint8Array(passwordBytes.length + salt.length)
      combined.set(passwordBytes)
      combined.set(salt, passwordBytes.length)

      let digest = await crypto.subtle.digest('SHA-256', combined)
      for (let round = 0; round < 10000; round++) {
        digest = await crypto.subtle.digest('SHA-256', digest)
      }

      const actual = new Uint8Array(digest)
      return { valid: timingSafeEqual(actual, expected), needsRehash: true }
    }
  } catch {
    // Continue to the legacy unsalted format check below.
  }

  if (/^[a-f0-9]{64}$/i.test(storedHash)) {
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(password))
    const actual = Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('')
    return { valid: timingSafeEqual(new TextEncoder().encode(actual), new TextEncoder().encode(storedHash.toLowerCase())), needsRehash: true }
  }

  return { valid: false, needsRehash: false }
}

function timingSafeEqual(left: Uint8Array, right: Uint8Array): boolean {
  if (left.length !== right.length) return false
  let difference = 0
  for (let index = 0; index < left.length; index++) {
    difference |= (left[index] ?? 0) ^ (right[index] ?? 0)
  }
  return difference === 0
}
